// هذا هو محتوى ملف codes.js - النسخة الكاملة والمحدثة بأكثر من 450 كود
const allCodeData = {
    'shapes-graphics-codes': [
        { title: 'سماء وغيوم', id: 'shape-sky', template: '[c][6CABDD]☁️      ☁️\n[b]  {{TEXT}}\n[6CABDD]   ☁️      ☁️', defaultText: 'YourName', keywords: ['غيم', 'سحاب'] },
        { title: 'شمس مشرقة', id: 'shape-sun', template: '[c][FFFF00]☀️\n[b][FFA500]S U N S H I N E', keywords: ['صيف'] },
        { title: 'كوكب الفضاء', id: 'shape-planet', template: '[c][5865F2]🪐\n[b][FFFFFF]G A L A X Y', keywords: ['نجم', 'نجوم'] },
        { title: 'سلاح رشاش', id: 'shape-gun', template: '[c][A0A0A0]︻╦╤─ ─ ─', keywords: ['بندقية'] },
        { title: 'قلب كهربائي', id: 'shape-e-heart', template: '[c][00F2EA]__̴ı̴̴̡̡̡ ̡͌l̡̡̡ ̡͌l̡*̡̡ ̴̡ı̴̴̡ ̡̡͡|̲̲̲͡͡͡ ̲▫̲͡ ̲̲̲͡͡π̲̲͡͡ ̲̲͡▫̲̲͡͡ ̲|̡̡̡ ̡ ̴̡ı̴̡̡ ̡͌l̡̡̡̡.__', keywords: ['نبض'] },
        { title: 'برق ورعد', id: 'shape-thunder', template: '[c][FFFF00]⚡️ [b]T H U N D E R [FFFF00]⚡️', keywords: ['صاعقة'] },
        { title: 'نار مشتعلة', id: 'shape-fire', template: '[c][FFA500]🔥🔥🔥\n[b][FF0000]F I R E', keywords: [] },
        { title: 'قطرة ماء', id: 'shape-water', template: '[c][00aaff]💧\n[b][FFFFFF]W A T E R', keywords: ['مطر'] },
        { title: 'ورقة شجر', id: 'shape-leaf', template: '[c][00FF00]☘️\n[b][FFFFFF]N A T U R E', keywords: ['طبيعة'] },
        { title: 'تاج ملكي', id: 'shape-crown', template: '[c][FFD700]👑\n[b][FFFFFF]K I N G', keywords: ['ملك'] },
        { title: 'سيف المحارب', id: 'shape-sword', template: '[c][A0A0A0]o===[FFFFFF]::::::::::::>[A0A0A0]', keywords: ['سيف'] },
        { title: 'موجة صوتية', id: 'shape-soundwave', template: '[c][FF00FF]▂▃▅▆█[FFFFFF] MUSIC [FF00FF]█▆▅▃▂', keywords: ['موسيقى', 'صوت'] },
        { title: 'يين ويانغ', id: 'shape-yinyang', template: '[c][FFFFFF]☯︎', keywords: ['توازن'] },
        { title: 'هيكل عظمي راقص', id: 'shape-dance-skull', template: '[c][FFFFFF]༼[A0A0A0]ᕗ[FFFFFF]༽[A0A0A0]ᕗ[FFFFFF]༽ ༼[A0A0A0]ᕗ[FFFFFF]༽[A0A0A0]ᕗ', keywords: ['جمجمة', 'رقص'] },
        { title: 'قناع غامض', id: 'shape-mask', template: '[c][000000]█[A0A0A0]█[000000]█[A0A0A0]█\n[b][FFFFFF]ANONYMOUS', keywords: ['مجهول'] },
        { title: 'كود موسيقى', id: 'shape-music-notes', template: '[c][FF00FF]♪[00F2EA]♫[FF00FF]♩[00F2EA]♪' },
        { title: 'صاروخ فضاء', id: 'shape-rocket', template: '[c][A0A0A0]    /\\\n   /  \\\n[FFFFFF]  /____\\\n  [E1D9D1] |    |\n   |    |\n[FF9933]  /|/\\|\\', keywords: ['فضاء'] },
        { title: 'سيارة سباق', id: 'shape-racecar', template: '[c][FF0000]__\n[A0A0A0]o-[FFFFFF]~\\_[A0A0A0]_____\n[FFFFFF]  (●)________(●)', keywords: ['سياره'] },
        { title: 'وجه قطة (Kaomoji)', id: 'shape-cat-face', template: '[c][FFFFFF]=＾● ⋏ ●＾=', keywords: ['قطة', 'بسة'] },
        { title: 'بروفايل النسر الذهبي', id: 'new-eagle', template: '[FFD700]█▄◯╲╱☰[FFFFFF]\n{{TEXT}}', defaultText: 'YOUR NAME', keywords: ['صقر'] },
        { title: 'كود خطر ☣️', id: 'new-biohazard', template: '[b][c][FFFF00]BIOHAZARD\n[FFFFFF]    ☣︎', keywords: ['سام'] },
        { title: 'كود أجنحة الملاك', id: 'new-angel-wings', template: '[c][FFFFFF]╲ [FFD700]A N G E L[FFFFFF] ╱', keywords: ['جناح'] },
        { title: 'كود THE FLASH', id: 'new-flash', template: '[b][c][FFD700]THE FLASH\n      ⚡️', keywords: ['فلاش', 'سريع'] },
        { title: 'رمز الإشعاع', id: 'new-radiation', template: '[b][c][00FF00]TOXIC\n[FFFF00]    ☢︎', keywords: ['نووي'] },
        { title: 'رمز لا نهائي', id: 'new-infinity', template: '[b][c][00F2EA]INFINITY\n[FFFFFF]    ∞', keywords: ['انفنتي'] },
        { title: 'رمز درع المحارب', id: 'new-shield', template: '[b][c][6D7B8D]WARRIOR\n[FFFFFF]     🛡︎', keywords: ['درع'] },
        { title: 'رمز القنبلة', id: 'new-bomb', template: '[b][c][FF0000]DANGER\n[000000]     💣', keywords: ['قنبله'] },
        { title: 'رمز الماس', id: 'new-diamond', template: '[b][c][00F2EA]DIAMOND\n[FFFFFF]     💎', keywords: ['الماس'] },
        { title: 'رمز الجمجمة', id: 'new-skull', template: '[b][c][FFFFFF]DANGER\n[A0A0A0]     💀', keywords: ['جمجمة'] },
        { title: 'شريط الطاقة ⚡', id: 'power-string', template: '[b][c][FF0099]╭────╮\n  |  ⚡︎  STRING  ≡≡▊\n╰────╯', keywords: ['باور'] },
        { title: 'رجل النجاح', id: 'success-man', template: '[b][00FFFF]╬═╬ ☺️/\n╬═╬ /▌SUCCESS\n[00FF7F]╬═╬ / \\', keywords: ['ناجح'] },
        { title: 'رموز ذهبية 999', id: 'golden-symbols', template: '[FFB900][b]ㅤ✿ ㅤ  ♬ ㅤ  ☯︎ [/b][c]\n    999ㅤ999ㅤ999', keywords: ['ذهب'] },
        { title: 'I LIKE YOU', id: 'i-like-you', template: '[c][CCFF00]ꦻꦿ[00FFFF]Ｉ ＬＩＫＥ ＹＯＵ[CCFF00]ꦻꦿ' },
        { title: 'FREE FIRE MAX', id: 'ff-max', template: '[b][c][ffd700]ＦＲＥＥ  ＦＩＲＥ\n      ██◣ MAX ◢██' },
        { title: 'FREE FIRE مزخرف', id: 'ff-art-1', template: 'FREE F[FFA500]I[FFFFFF]RE'},
        { title: 'شعار فني 1', id: 'ff-art-2', template: '[CCFF00]_____◢▓▓▓▓▓◣   ▙\n◤     ◥▙▛▀▀▜▛▔▔'},
        { title: 'وجه متجاهل (Kaomoji)', id: 'shape-shrug', template: '[c][b][FFFFFF]¯\\_(ツ)_/¯', keywords: ['لا أعرف'] },
        { title: 'قلب وردة', id: 'shape-rose-heart', template: '[c][FF4F8B]--<-`--<@', keywords: ['ورد'] },
        { title: 'وجه غاضب (Kaomoji)', id: 'shape-angry', template: '[c][FFFFFF](╯°□°)╯︵ ┻━┻', keywords: ['غضب'] },
        { title: 'شكل صليب', id: 'shape-cross', template: '[c][A0A0A0]      t\n[b][FFFFFF]✞ MEMENTO MORI ✞', keywords: ['صليب'] },
        { title: 'شكل دب (Kaomoji)', id: 'shape-bear', template: '[c][FFFFFF](ᵔᴥᵔ)', keywords: ['دب'] },
        { title: 'ستايل جمالي', id: 'shape-aesthetic', template: '[b][c][FF00FF]ＡＥＳＴＨＥＴＩＣ', keywords: ['جمالي'] },
        { title: 'ستايل فابورويف', id: 'shape-vaporwave', template: '[b][c][00F2EA]ＶＡＰＯＲＷＡＶＥ', keywords: ['فابور'] },
        { title: 'شكل فراشة', id: 'shape-butterfly', template: '[c][FF00FF]Ƹ̵̡Ӝ̵̨̄Ʒ', keywords: ['فراشة'] },
        { title: 'شكل ميزان موسيقى', id: 'shape-equalizer', template: '[c][33CC99]ılı.lıllılı.ıllı', keywords: ['موسيقى'] },
        { title: 'ملاحظات موسيقية', id: 'shape-music-notes-2', template: '[c][b][FFFFFF]♫♪.ılılıll|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅|llılılı.♫♪', keywords: ['أغنية'] },
        { title: 'وجه يبكي (Kaomoji)', id: 'shape-crying', template: '[c][FFFFFF]( T _ T )', keywords: ['حزين', 'بكي'] },
        { title: 'أرنب لطيف (Kaomoji)', id: 'shape-bunny', template: '[c][FFFFFF](\\__/) \n(  =\'.\'=)\n(")_(")', keywords: ['أرنب'] },
        { title: 'شعار باتمان فني', id: 'shape-batman-art', template: '[c][000000]    .--. \n   |o_o | \n   |:_/ | \n  //   \\ \\ \n (|     | ) \n/\'\\_   _/\'\\ \n\\___)=(___/', keywords: ['باتمان'] },
        { title: 'شكل شبح', id: 'shape-ghost', template: '[c][FFFFFF] .-.\n(o o) boo!\n| O \\\n \\   \\\n  `~~~`', keywords: ['شبح'] },
        { title: 'كود قهوة', id: 'shape-coffee', template: '[c][6D7B8D]   .-.    \n  (   )   \n   `~`    \n[E1D9D1]c[_] COFFEE', keywords: ['قهوة'] },
        { title: 'بروفايل مخلب', id: 'shape-claw', template: '[b][c][A0A0A0]爪 [FFFFFF]C L A W [A0A0A0]爪' },
        { title: 'شكل سحابة رعدية', id: 'shape-storm-cloud', template: '[c][A0A0A0]  .--.    \n.-(  _).-. \n( ´    ) `)\n ` ._.) .´  \n[FFFF00]    ⚡️', keywords: ['عاصفة'] },
        { title: 'وجه مبتسم بسيط', id: 'shape-smiley', template: '[c][FFFF00]:-)', keywords: ['سعيد'] },
        { title: 'شعار قرصان فني', id: 'shape-pirate-flag', template: '[c][FFFFFF]   / \\\n  / _ \\\n | ( ) |\n  \\_-_/ \n[000000]   / \\\n  /   \\\n /     \\', keywords: ['قرصان', 'جمجمة'] },
        { title: 'رمز السلام', id: 'shape-peace', template: '[c][00aaff]☮︎ PEACE', keywords: ['سلام'] },
        { title: 'شكل UFO', id: 'shape-ufo', template: '[c][A0A0A0]    .    \n   .:.   \n.´¯`:´¯`.\n`-. `.` .-\'\n   `·´   ', keywords: ['فضائي'] },
        { title: 'مفتاح صول', id: 'shape-sol-key', template: '[c][FFD700]𝄞', keywords: ['موسيقى'] },
        // --- 50 NEW SHAPE/ART CODES ---
        { title: 'كود موجة البحر', id: 'shape-wave', template: '[c][00aaff]~ ~ ~ ~ [FFFFFF]Wave [00aaff]~ ~ ~ ~', keywords: ['بحر'] },
        { title: 'إطار نيون', id: 'shape-neon-frame', template: '[c][b][00F2EA]╔═══════╗\n  [FFFFFF]{{TEXT}}\n[00F2EA]╚═══════╝', defaultText: 'NEON', keywords: ['إطار', 'نيون'] },
        { title: 'قلب بكسل ملون', id: 'shape-pixel-heart-color', template: '[c][FF0000]██ [FF4F8B]██\n[FF0000]████[FF4F8B]██\n [FF0000]██[FF4F8B]██\n  [FF0000]██', keywords: ['بكسل'] },
        { title: 'وجه نائم', id: 'shape-sleeping', template: '[c][FFFFFF](-.-) Zzz...', keywords: ['نوم'] },
        { title: 'رمز العنكبوت', id: 'shape-spider', template: '[c][A0A0A0]/\\/\\(,,,)/\\/\\', keywords: ['عنكبوت'] },
        { title: 'شكل جوهرة', id: 'shape-gem', template: '[c][00F2EA]  /\\\n /__\\\n(____)', keywords: ['جوهرة'] },
        { title: 'شكل لهب أزرق', id: 'shape-blue-flame', template: '[c][00aaff]🔥\n[b][FFFFFF]Blue Fire', keywords: ['لهب'] },
        { title: 'رمز الذرة', id: 'shape-atom', template: '[c][FFFFFF]⚛︎', keywords: ['علم'] },
        { title: 'مظلة', id: 'shape-umbrella', template: '[c][FF4F8B]☂︎', keywords: ['مظلة'] },
        { title: 'وجه سعيد', id: 'shape-happy-face', template: '[c][FFFF00](^▽^)', keywords: ['سعيد'] },
        { title: 'إطار مزخرف', id: 'shape-deco-frame', template: '[c][b][FFD700]·.¸¸.·´¯`·.¸¸.·\n  [FFFFFF]{{TEXT}}\n[FFD700]·.¸¸.·´¯`·.¸¸.·', defaultText: 'Style', keywords: ['زخرفة', 'إطار'] },
        { title: 'شكل ألماسة', id: 'shape-diamond-2', template: '[c][6CABDD]  /\\\n <  >\n  \\/', keywords: ['ألماس'] },
        { title: 'وجه يغمز', id: 'shape-wink', template: '[c][FFFF00](^_-)', keywords: ['غمزة'] },
        { title: 'رمز راديوأكتيف', id: 'shape-radioactive', template: '[c][FFFF00]☢︎', keywords: ['نووي'] },
        { title: 'شكل القمر', id: 'shape-moon', template: '[c][E1D9D1]   _.._\n .\'    `.\n`        `', keywords: ['قمر'] },
        { title: 'شكل كريستالة', id: 'shape-crystal', template: '[c][FF00FF]🔮', keywords: ['كريستال'] },
        { title: 'وجه محتار', id: 'shape-confused', template: '[c][FFFFFF](o_O)?', keywords: ['محتار'] },
        { title: 'شكل برج', id: 'shape-tower', template: '[c][A0A0A0]   /\\ \n  /  \\ \n /____\\ \n  ||||  \n  ||||  ', keywords: ['برج'] },
        { title: 'رمز البريد', id: 'shape-mail', template: '[c][FFFFFF]✉︎', keywords: ['رسالة'] },
        { title: 'شكل طائرة ورقية', id: 'shape-kite', template: '[c][FF0000]  /\\\n /__\\\n  /\\ \n  \\/', keywords: ['طائرة'] },
        { title: 'كود واي فاي كامل', id: 'shape-wifi-full', template: '[c][FFFFFF]   ((•))\n    📶', keywords: ['واي فاي'] },
        { title: 'وجه ملاك', id: 'shape-angel-face', template: '[c][FFD700]O:)', keywords: ['ملاك'] },
        { title: 'رمز إعادة التدوير', id: 'shape-recycle', template: '[c][00FF00]♻︎', keywords: ['بيئة'] },
        { title: 'شكل سمكة', id: 'shape-fish', template: '[c][6CABDD]><(((°>', keywords: ['سمك'] },
        { title: 'شكل صاروخ بسيط', id: 'shape-rocket-simple', template: '[c][A0A0A0]∆', keywords: ['صاروخ'] },
        { title: 'شكل مفتاح', id: 'shape-key', template: '[c][FFD700]🔑', keywords: ['مفتاح'] },
        { title: 'وجه شيطان', id: 'shape-devil-face', template: '[c][FF0000]>:)', keywords: ['شيطان'] },
        { title: 'رمز لايك', id: 'shape-like', template: '[c][00aaff]👍', keywords: ['لايك'] },
        { title: 'شكل قفل', id: 'shape-lock', template: '[c][A0A0A0]🔒', keywords: ['قفل'] },
        { title: 'رمز دي ان ايه', id: 'shape-dna', template: '[c][33CC99]⚚', keywords: ['DNA'] },
        { title: 'شكل منزل', id: 'shape-house', template: '[c][E1D9D1]   /\\ \n  /  \\ \n |----| \n |[] |', keywords: ['منزل'] },
        { title: 'رمز حقوق النشر', id: 'shape-copyright', template: '[c][A0A0A0]©', keywords: ['حقوق'] },
        { title: 'شكل قمر هلال', id: 'shape-crescent', template: '[c][FFFF00]☾', keywords: ['هلال'] },
        { title: 'رمز هدف', id: 'shape-target', template: '[c][FF0000]🎯', keywords: ['هدف'] },
        { title: 'كوكب زحل', id: 'shape-saturn', template: '[c][F8D300]♄', keywords: ['زحل'] },
        { title: 'رمز رجل', id: 'shape-man', template: '[c][00aaff]♂', keywords: ['رجل'] },
        { title: 'رمز امرأة', id: 'shape-woman', template: '[c][FF4F8B]♀', keywords: ['امرأة'] },
        { title: 'زخرفة خطوط', id: 'shape-line-deco', template: '[c][A0A0A0]═.♥.═', keywords: ['زخرفة'] },
        { title: 'رمز تيك', id: 'shape-checkmark', template: '[c][00FF00]✓', keywords: ['صح'] },
        { title: 'رمز خطأ', id: 'shape-x-mark', template: '[c][FF0000]✗', keywords: ['خطأ'] },
        { title: 'وجه يبكي من الضحك', id: 'shape-lol-face', template: '[c][FFFF00](😂)', keywords: ['ضحك'] },
        { title: 'رمز انفينتي مزخرف', id: 'shape-infinity-deco', template: '[c][FF00FF]꧁∞꧂', keywords: ['انفنتي'] },
        { title: 'شكل شمعة', id: 'shape-candle', template: '[c][FFFF00]🕯️', keywords: ['شمعة'] },
        { title: 'شكل ندفة ثلج', id: 'shape-snowflake', template: '[c][00F2EA]❄️', keywords: ['ثلج'] },
        { title: 'رمز القوة', id: 'shape-power', template: '[c][FFFF00]⚡', keywords: ['قوة'] },
        { title: 'وجه مع نظارة', id: 'shape-cool-face', template: '[c][000000](⌐■_■)', keywords: ['كوول'] },
        { title: 'رمز الجيتار', id: 'shape-guitar', template: '[c][6D7B8D]🎸', keywords: ['جيتار'] },
        { title: 'شكل فأر', id: 'shape-mouse', template: '[c][A0A0A0]<:3 )~', keywords: ['فأر'] },
        { title: 'رمز الباندا', id: 'shape-panda', template: '[c][FFFFFF]🐼', keywords: ['باندا'] }
    ],
    'sports-clubs-codes': [
        { title: 'الهلال السعودي', id: 'club-hilal', template: '[b][0000FF] زعيم آسيا 🇸🇦\n[FFFFFF] {{TEXT}}', defaultText: 'Al-Hilal', keywords: ['هلال'] },
        { title: 'النصر السعودي', id: 'club-nassr', template: '[b][FFFF00] العالمي 🇸🇦\n[0000FF] {{TEXT}}', defaultText: 'Al-Nassr', keywords: ['نصر'] },
        { title: 'الأهلي المصري', id: 'club-ahly-egy', template: '[b][FF0000] نادي القرن 🇪🇬\n[FFFFFF] {{TEXT}}', defaultText: 'Al-Ahly', keywords: ['اهلي'] },
        { title: 'الزمالك المصري', id: 'club-zamalek', template: '[b][FFFFFF] الفن والهندسة 🇪🇬\n[FF0000] {{TEXT}}', defaultText: 'Zamalek', keywords: [] },
        { title: 'مانشستر سيتي', id: 'club-mancity', template: '[b][6CABDD]Man City\n[FFFFFF] {{TEXT}}', defaultText: 'Citizens', keywords: ['مان سيتي'] },
        { title: 'ليفربول', id: 'club-liverpool', template: '[b][D30000]YNWA\n[FFFFFF] {{TEXT}}', defaultText: 'Liverpool', keywords: ['صلاح'] },
        { title: 'بايرن ميونخ', id: 'club-bayern', template: '[b][E2001A]Mia San Mia\n[FFFFFF] {{TEXT}}', defaultText: 'Bayern', keywords: ['بايرن'] },
        { title: 'باريس سان جيرمان', id: 'club-psg', template: '[b][004B87]ICI C\'EST [E30613]PARIS\n[FFFFFF] {{TEXT}}', defaultText: 'PSG', keywords: ['باريس'] },
        { title: 'الاتحاد السعودي', id: 'club-ittihad', template: '[b][000000]█[FFFF00]█\n[FFFFFF] {{TEXT}}', defaultText: 'Ittihad', keywords: ['اتي', 'اتحاد'] },
        { title: 'الرجاء المغربي', id: 'club-raja', template: '[b][008000]Dima Raja 🇲🇦\n[FFFFFF] {{TEXT}}', defaultText: 'RCA', keywords: [] },
        { title: 'الوداد المغربي', id: 'club-wydad', template: '[b][FF0000]Dima Wydad 🇲🇦\n[FFFFFF] {{TEXT}}', defaultText: 'WAC', keywords: [] },
        { title: 'مانشستر يونايتد', id: 'club-manutd', template: '[b][DA291C]Man United\n[FFFFFF] {{TEXT}}', defaultText: 'Red Devils', keywords: ['يونايتد'] },
        { title: 'تشيلسي', id: 'club-chelsea', template: '[b][003D73]Chelsea FC\n[FFFFFF] {{TEXT}}', defaultText: 'The Blues', keywords: [] },
        { title: 'أرسنال', id: 'club-arsenal', template: '[b][EF4135]Arsenal\n[FFFFFF] {{TEXT}}', defaultText: 'Gunners', keywords: [] },
        { title: 'يوفنتوس', id: 'club-juventus', template: '[b][000000]Juve\n[FFFFFF] {{TEXT}}', defaultText: 'Forza Juve', keywords: [] },
        { title: 'ستايل رونالدو', id: 'ronaldo-style', template: '[009c3b]█[ffdf00]༃[ff0000]█ {{TEXT}}亗', defaultText: 'CR7', keywords: ['كرستيانو'] },
        { title: 'برشلونة', id: 'barca', template: '[b]{{TEXT}}\n[A50044]██[004D98]██\n[004D98]██[A50044]██', defaultText: 'F.C.B', keywords: ['برشا', 'barcelona'] },
        { title: 'ريال مدريد', id: 'real', template: '[b]{{TEXT}}\n[FFFFFF]██[0A1A57]██\n[0A1A57]██[FFFFFF]██', defaultText: 'R.M.A', keywords: ['مدريد', 'ريل', 'real madrid'] },
        { title: 'إنتر ميلان', id: 'club-inter', template: '[b][0000FF]█[000000]█\n[FFFFFF] Inter Milan', keywords: ['انتر'] },
        { title: 'إيه سي ميلان', id: 'club-milan', template: '[b][FF0000]█[000000]█\n[FFFFFF] AC Milan', keywords: ['ميلان'] },
        { title: 'بروسيا دورتموند', id: 'club-bvb', template: '[b][FFFF00]█[000000]█\n[FFFFFF] Dortmund', keywords: ['دورتموند'] },
    ],
    'country-flags-codes': [
        { title: 'علم السعودية 🇸🇦', id: 'flag-ksa', template: '[b][006F2A]█🇸🇦█\n[FFFFFF] {{TEXT}}', defaultText: 'K.S.A', keywords: ['سعوديه'] },
        { title: 'علم مصر 🇪🇬', id: 'flag-egypt', template: '[b][FF0000]█[FFFFFF]█[000000]█\n[FFD700] {{TEXT}}', defaultText: 'EGY', keywords: [] },
        { title: 'علم المغرب 🇲🇦', id: 'flag-morocco', template: '[b][FF0000]█[008000]★[FF0000]█\n[FFFFFF] {{TEXT}}', defaultText: 'MAR', keywords: [] },
        { title: 'علم الجزائر 🇩🇿', id: 'flag-algeria', template: '[b][00FF00]█[FFFFFF]☪[FFFFFF]█[FF0000]█\n[FFFFFF] {{TEXT}}', defaultText: 'DZA', keywords: [] },
        { title: 'علم تونس 🇹🇳', id: 'flag-tunisia', template: '[b][FF0000]█☪█\n[FFFFFF] {{TEXT}}', defaultText: 'TUN', keywords: [] },
        { title: 'علم العراق 🇮🇶', id: 'flag-iraq', template: '[b][FF0000]█[FFFFFF]الله أكبر[FFFFFF]█[000000]█\n[00FF00] {{TEXT}}', defaultText: 'IRQ', keywords: [] },
        { title: 'علم فلسطين 🇵🇸', id: 'flag-palestine', template: '[b][000000]█[FFFFFF]█[008000]█\n[FF0000]▶[FFFFFF] {{TEXT}}', defaultText: 'PSE', keywords: [] },
        { title: 'علم الإمارات 🇦🇪', id: 'flag-uae', template: '[b][FF0000]█[008000]█[FFFFFF]█[000000]█\n[FFFFFF] {{TEXT}}', defaultText: 'U.A.E', keywords: ['امارات'] },
        { title: 'علم سوريا 🇸🇾', id: 'flag-syria', template: '[b][FF0000]█[FFFFFF]★★[FFFFFF]█[000000]█\n[00FF00] {{TEXT}}', defaultText: 'SYR', keywords: [] },
        { title: 'علم الأردن 🇯🇴', id: 'flag-jordan', template: '[b][000000]█[FFFFFF]█[008000]█\n[FF0000]▶[FFFFFF] {{TEXT}}', defaultText: 'JOR', keywords: [] },
        { title: 'علم الكويت 🇰🇼', id: 'flag-kuwait', template: '[b][008000]█[FFFFFF]█[FF0000]█\n[000000]▶[FFFFFF] {{TEXT}}', defaultText: 'KWT', keywords: [] },
        { title: 'علم البرازيل 🇧🇷', id: 'flag-brazil', template: '[b][009C3B]█[FFDF00]◆[009C3B]█\n[FFFFFF] {{TEXT}}', defaultText: 'BRA', keywords: [] },
        { title: 'علم الأرجنتين 🇦🇷', id: 'flag-argentina', template: '[b][6CABDD]█[FFFFFF]☀️[FFFFFF]█[6CABDD]█\n[000000] {{TEXT}}', defaultText: 'ARG', keywords: ['ميسي'] },
        { title: 'علم البرتغال 🇵🇹', id: 'flag-portugal', template: '[b][006F2A]█[FF0000]█\n[FFFFFF] {{TEXT}}', defaultText: 'POR', keywords: ['رونالدو'] },
        { title: 'علم ألمانيا 🇩🇪', id: 'flag-germany', template: '[B][000000]███\n[FF0000]███{{TEXT}}\n[FFCC00]███', defaultText: 'G.E.R', keywords: ['المانيا'] },
        { title: 'علم فرنسا 🇫🇷', id: 'flag-france', template: '[b]{{TEXT}}\n[0055A4]██[FFFFFF]██[EF4135]██', defaultText: 'F.R.A' },
        { title: 'علم إيطاليا 🇮🇹', id: 'flag-italy', template: '[b]{{TEXT}}\n[009246]██[FFFFFF]██[CD212A]██', defaultText: 'I.T.A' },
    ],
    'love-codes': [
        { title: 'حب أبدي', id: 'love-forever', template: '[FF4F8B]❤[FFFFFF] {{TEXT}} [FF4F8B]❤\n[c][FFFFFF]F O R E V E R', defaultText: 'You & Me' },
        { title: 'قلب مكسور', id: 'love-broken-heart', template: '[b][c][A0A0A0]BROKEN\n[FF0000]💔' },
        { title: 'أحبك', id: 'love-1', template: '[b][c][FF0000]I [FFFFFF]LOVE [FF0000]YOU' },
        { title: 'ملكي/ملكتي', id: 'love-2', template: '[b][c][FFD700]My {{TEXT}} 👑', defaultText: 'Queen' },
        { title: 'نصفي الآخر', id: 'love-3', template: '[c][FF4F8B]My [FFFFFF]Other Half' },
        { title: 'قلبي', id: 'love-4', template: '[b][FF0000]❤ [FFFFFF]My Heart [FF0000]❤' },
        { title: 'أنت لي', id: 'love-5', template: '[b][c][FF4F8B]Y[FFFFFF]O[FF4F8B]U [FFFFFF]ARE [FF4F8B]M[FFFFFF]I[FF4F8B]N[FFFFFF]E' },
        { title: 'معا إلى الأبد', id: 'love-6', template: '[c][b][FFFFFF]Together [FFD700]Forever' },
        { title: 'رسمة قلب كبير', id: 'love-art-1', template: '[c][FF0000]██[FFFFFF]██[FF0000]██[FFFFFF]██\n[FF0000]██[FFFFFF]██[FF0000]██[FFFFFF]██[FF0000]██\n [FF0000]██[FFFFFF]██[FF0000]██[FFFFFF]██\n  [FF0000]██[FFFFFF]██\n   [FF0000]█' },
        { title: 'مفتاح قلبي', id: 'love-7', template: '[c][b][FFD700]🔑 [FFFFFF]The key to my [FF0000]❤' },
        { title: 'توأم روحي', id: 'love-8', template: '[b][c][FF4F8B]S O U L M A T E' },
        { title: 'قصة حبنا', id: 'love-9', template: '[c][FFFFFF]Our Love Story [FF0000]❤' },
        { title: 'الحب هو كل شيء', id: 'love-10', template: '[b][FF0000]L[FFFFFF]O[FF0000]V[FFFFFF]E [A0A0A0]is all you need' },
        { title: 'أنت عالمي', id: 'love-11', template: '[c][b][00aaff]You are my [FFFFFF]World 🌏' },
        { title: 'حب لا نهائي', id: 'love-12', template: '[c][b][FF4F8B]∞ [FFFFFF]Infinite Love [FF4F8B]∞' },
        { title: 'أنت وأنا', id: 'love-names', template: '[b][c][FFFFFF]{{NAME1}} [FF0000]❤ [FFFFFF]{{NAME2}}', defaultText: 'Player1,Player2' },
        { title: 'نبضات القلب', id: 'love-beat', template: '[c][FF0000]__/\u001B\u001B__/\u001B\u001B__' },
        { title: 'خاتم الحب', id: 'love-ring', template: '[b][c][FFD700]Will you marry me?\n      💍' },
        { title: 'ملكة قلبي', id: 'love-queen-heart', template: '[b][c][FFD700]Queen [FFFFFF]of my [FF0000]❤' },
        { title: 'ملك قلبي', id: 'love-king-heart', template: '[b][c][FFD700]King [FFFFFF]of my [FF0000]❤' },
        { title: 'أحبك أكثر', id: 'love-more', template: '[b][c][FF4F8B]I Love You More' },
        { title: 'أنت شمسي', id: 'love-sunshine', template: '[b][c][FFFF00]You are my ☀️' },
        { title: 'حبيبي/حبيبتي', id: 'love-darling', template: '[c][b][FF4F8B]My Darling {{TEXT}}', defaultText: '...' },
        { title: 'عناق وقبلات', id: 'love-xoxo', template: '[b][c][FF4F8B]XOXO' },
        { title: 'أفكر فيك', id: 'love-thinking', template: '[c][A0A0A0]Thinking of [FF0000]You...' },
        { title: 'أنت الأفضل', id: 'love-the-one', template: '[c][b][FFFFFF]You\'re [FFD700]The One' },
        { title: 'حب حقيقي', id: 'love-true', template: '[c][b][00aaff]T R U E  [FF0000]L O V E' },
        { title: 'ملاك حبي', id: 'love-angel', template: '[b][c][FFFFFF]My [FFD700]Angel' },
        { title: 'أنت قدري', id: 'love-destiny', template: '[c][b][FF00FF]You are my Destiny' },
        { title: 'قلبان معًا', id: 'love-two-hearts', template: '[c][b][FF0000]❤ [FFFFFF]+ [FF0000]❤' },
        { title: 'حب للأبد', id: 'love-eternity', template: '[b][c][FFFFFF]Love for [FFD700]Eternity' },
        { title: 'بيت الحب', id: 'love-house', template: '[b][c]╱◥██████◣\n[ffd319]│∩│▤│▤│▤\n▓▓▓▓▓▓▓▓▓ FF LOVE'},
        { title: 'أنتِ قمري', id: 'love-my-moon', template: '[b][c][FFFFFF]أنتِ [FFFF00]قمري 🌙', keywords: ['قمر'] },
        { title: 'حب مزخرف', id: 'love-arabic-art', template: '[c][FF4F8B]حُــب', keywords: [] },
        { title: 'مأخوذ ❤️', id: 'love-taken', template: '[b][c][A0A0A0]TAKEN [FF0000]❤', keywords: ['مرتبط'] },
        { title: 'أحرف متشابكة', id: 'love-initials', template: '[b][c][FFFFFF]{{NAME1}} [FF4F8B]& [FFFFFF]{{NAME2}}', defaultText: 'A,B', keywords: ['حرف'] },
        { title: 'أنتِ حياتي', id: 'love-my-life', template: '[b][c][FF4F8B]You are my [FFFFFF]Life', keywords: ['حياة'] },
        // --- 75 NEW LOVE CODES ---
        { title: 'حب بلا حدود', id: 'love-limitless', template: '[c][b][FF4F8B]L O V E\n[FFFFFF]WITHOUT LIMITS' },
        { title: 'أنت كل شيء', id: 'love-everything', template: '[c][b][FFFFFF]You are my [FFD700]Everything' },
        { title: 'قلب و سهم', id: 'love-heart-arrow', template: '[c][FF0000]❤🏹' },
        { title: 'شرارة حب', id: 'love-spark', template: '[c][b]You are my [FFFF00]spark ✨' },
        { title: 'فقط نحن الإثنان', id: 'love-just-us', template: '[c][b][FFFFFF]Just the [FF4F8B]Two [FFFFFF]of Us' },
        { title: 'أنت نصي الآخر', id: 'love-my-half', template: '[c][b]My Better Half [FF0000]❤' },
        { title: 'قصة حب لا تنتهي', id: 'love-endless-story', template: '[c][A0A0A0]An endless [FF4F8B]love [A0A0A0]story' },
        { title: 'حبي لك كالمجرة', id: 'love-galaxy', template: '[c][b][5865F2]My love for you is a galaxy' },
        { title: 'أنت كنزي', id: 'love-treasure', template: '[c][b]You are my [FFD700]treasure 💎' },
        { title: 'أنت أغنيتي', id: 'love-my-song', template: '[c][b][FF00FF]You are my song 🎶' },
        { title: 'حب مجنون', id: 'love-crazy', template: '[c][b][FF0000]CRAZY [FFFFFF]IN [FF0000]LOVE' },
        { title: 'دائما و ابدا', id: 'love-always-forever', template: '[c][b][A0A0A0]Always [FFFFFF]& [A0A0A0]Forever' },
        { title: 'قلبي يناديك', id: 'love-heart-calls', template: '[c][b]My [FF0000]heart [FFFFFF]calls for you' },
        { title: 'أنت حلمي', id: 'love-my-dream', template: '[c][b][00F2EA]You are my [FFFFFF]dream' },
        { title: 'معا ضد العالم', id: 'love-against-world', template: '[c][b][FFFFFF]You & Me vs The World' },
        { title: 'نبض قلبي', id: 'love-my-beat', template: '[c][b][FF0000]My [FFFFFF]Heartbeat' },
        { title: 'رسالة في زجاجة', id: 'love-bottle', template: '[c][6CABDD]Message in a bottle... I LOVE YOU' },
        { title: 'حب من أول نظرة', id: 'love-first-sight', template: '[c][b][FF4F8B]Love at first sight' },
        { title: 'أنت شمسي وقمري', id: 'love-sun-moon', template: '[c][b][FFFF00]My Sun [FFFFFF]& [A0A0A0]My Moon' },
        { title: 'سأختارك دائما', id: 'love-always-choose', template: '[c][b]I will always choose [FF0000]you.' },
    ],
    'gaming-status-codes': [
        { title: 'الحساب محظور', id: 'new-banned', template: '[b][c][FFA500]⚠ [FF0000]هذا الحساب محظور', keywords: ['بان', 'باند'] },
        { title: 'بروفايل أسطورة مزخرف', id: 'new-legend-fancy', template: '[b][c][FFD700]꧁༺{{TEXT}}༻꧂\n      ♛ L E G E N D ♛', defaultText: 'YourName', keywords: ['اسطوره'] },
        { title: 'بروفايل مقاتل', id: 'new-warrior', template: '[b][c][A0A0A0]—⚔︎ {{TEXT}} ⚔︎—\n[FF0000]      BORN TO FIGHT', defaultText: 'Warrior' },
        { title: 'بروفايل غامض', id: 'new-mystic', template: '[c][FF00FF]☾ [FFFFFF]{{TEXT}} [FF00FF]☽\n[b][5865F2]      乡 D R E A M E R 鄉', defaultText: 'Mystic' },
        { title: 'بروفايل ملكي 亗', id: 'new-royal-king', template: '[b][c][FFB900] K I N G\n[FFFFFF]      亗 {{TEXT}} 亗', defaultText: 'FF', keywords:['ملك'] },
        { title: 'بروفايل الشيطان', id: 'new-devil', template: '[b][c][FF0000]D E V I L\n[FFFFFF]◢[000000]■[FFFFFF]◤\n[FF0000]    Ψ' },
        { title: 'بروفايل VIP ملكي', id: 'new-vip', template: '[b][c][FFFF00]━═══❖«[FFFFFF]{{TEXT}}[FFFF00]»❖═══━', defaultText: 'V.I.P', keywords: ['في اي بي'] },
        { title: 'كود الجوكر', id: 'new-joker', template: '[c][00FF00]WHY SO [FF00FF]SERIOUS?\n[b][FFFFFF] HA HA HA' },
        { title: 'بروفايل التنين', id: 'new-dragon', template: '[b][c][00FF00]D[FF8C00]R[00FF00]A[FF8C00]G[00FF00]O[FF8C00]N\n[FFFFFF]    ◢▆█▆◣' },
        { title: 'بروفايل أسطورة 5 نجوم', id: 'new-legend-stars', template: '[b][c][FFD700]L E G E N D\n[FFFFFF]      ★ ★ ★ ★ ★', keywords: ['اسطوره'] },
        { title: 'بروفايل ساموراي', id: 'new-samurai', template: '[b][c][DA291C]S A M U R A I\n[FFFFFF]      [DA291C]日本刀' },
        { title: 'بروفايل القراصنة', id: 'new-pirate', template: '[b][c][6D7B8D]P I R A T E\n[FFFFFF]      ☠︎' },
        { title: 'بروفايل نيون', id: 'new-neon', template: '[b][c][00F2EA]N E O N [FF00FF]L I G H T S' },
        { title: 'بروفايل نار وثلج', id: 'new-fire-ice', template: '[b][c][FFA500]F I R E [00F2EA]& I C E' },
        { title: 'بروفايل NO MERCY', id: 'new-no-mercy', template: '[b][c][FF0000]N O  M E R C Y\n[FFFFFF]    - K I L L E R -' },
        { title: 'بروفايل مبرمج', id: 'new-coder', template: '[b][c][00FF00]<[FFFFFF]C O D E R[00FF00]/>' },
        { title: 'بروفايل HEADSHOT', id: 'new-headshot', template: '[b][c][FF0000]H E A D S H O T\n[FFFFFF]      🎯', keywords: ['هيدشوت'] },
        { title: 'بروفايل مقاتل الظل', id: 'new-shadow', template: '[b][c][A0A0A0]S H A D O W\n[000000]█[A0A0A0]█[000000]█[A0A0A0]█[000000]█\n[A0A0A0]      ⚔︎' },
        { title: 'بروفايل لاعب فورتنايت', id: 'new-fortnite', template: '[b][c][FF00FF]FORT[00F2EA]NITE\n[FFFFFF]    ⛏️' },
        { title: 'كود لا تستسلم', id: 'new-never-give-up', template: '[b][c]NEVER\n[FFD700]GIVE\n[FFFFFF]UP' },
        { title: 'كود ONE SHOT', id: 'new-one-shot', template: '[b][c][FFFFFF]ONE SHOT\n[FF0000]ONE KILL' },
        { title: 'كود ستايل B2K', id: 'new-b2k-style', template: '[b][c][FF0000]B[FFFFFF]2[0000FF]K\n[A0A0A0]Born To Kill' },
        { title: 'كود Gamer Zone', id: 'new-gamer-zone', template: '[b][c][00FF00]█ G A M E R █\n[FFFFFF]█ Z O N E █' },
        { title: 'حالة: متصل', id: 'status-online', template: '[b][00FF00]● ONLINE' },
        { title: 'حالة: مشغول', id: 'status-busy', template: '[b][FFD700]● BUSY' },
        { title: 'كود LOADING...', id: 'new-loading', template: '[b][c][A0A0A0]Loading...\n[00FF00]█████▒▒▒▒▒' },
        { title: 'كود الوحش', id: 'new-beast', template: '[b][c][008000]B E A S T\n[FFFFFF]    MODE' },
        { title: 'كود سولو ضد سكواد', id: 'new-solo-squad', template: '[b][c]SOLO\n[FF0000]vs\n[FFFFFF]SQUAD' },
        { title: 'كود الذئب المنفرد', id: 'new-lone-wolf', template: '[b][c][A0A0A0]LONE WOLF\n[FFFFFF]      🐺' },
        { title: 'كود أسطورة لا تموت', id: 'new-legends-never-die', template: '[c][b][FFD700]Legends\n[A0A0A0]Never Die' },
        { title: 'رمز باتمان', id: 'new-batman', template: '[b][c][FFFF00]I\'M BATMAN\n[000000]    ◥🦇◤' },
        { title: 'GAME OVER', id: 'game-over', template: '[b][c][FF0000]G A M E\nO V E R', keywords: ['خسرت'] },
        { title: 'ملك الكلاتش 1 ضد 4', id: 'clutch-king', template: '[b][c][FFFF00]1v4\n[FFFFFF]CLUTCH KING', keywords: ['كلتش'] },
        { title: 'لاعب موبايل', id: 'mobile-gamer', template: '[b][c][00aaff]MOBILE\n[FFFFFF]LEGEND 📱', keywords: ['جوال'] },
        { title: 'لاعب بي سي', id: 'pc-gamer', template: '[b][c][FF00FF]PC MASTER\n[FFFFFF]RACE ⌨️', keywords: ['كمبيوتر'] },
        { title: 'حالة: AFK', id: 'status-afk', template: '[b][A0A0A0]● AFK', keywords: ['بعيد'] },
        { title: 'حالة: ألعب', id: 'status-grinding', template: '[b][00FF00]● GRINDING', keywords: ['ألعب'] },
        { title: 'لاعب بوت', id: 'bot-player', template: '[c][A0A0A0]I\'M A BOT 🤖', keywords: ['بوت'] },
        { title: 'اسم نينجا مزخرف', id: 'ninja-name', template: '[b][c][000000]乡•[FFFFFF]{{TEXT}}[000000]•鄉', defaultText: 'NINJA', keywords: ['نينجا'] },
        { title: 'اسم إله مزخرف', id: 'god-name', template: '[b][c][FFD700]么[FFFFFF]G O D[FFD700]么', keywords: ['إله'] },
        { title: 'اسم شبح مزخرف', id: 'phantom-name', template: '[b][c][A0A0A0]『[FFFFFF]PHANTOM[A0A0A0]』', keywords: ['شبح'] },
        { title: 'ملك الطلقة الواحدة', id: 'one-tap-king', template: '[b][c][FF0000]ONE TAP\n[FFFFFF]KING', keywords: ['ون تب'] },
        { title: 'مستوى عالي', id: 'max-level', template: '[b][c][FFD700]LEVEL\n[FFFFFF]   99', keywords: ['لفل'] },
        { title: 'بروفايل سايبربنك', id: 'cyberpunk-style', template: '[b][c][00F2EA]C Y B E R\n[FF00FF]P U N K', keywords: ['سايبر'] },
        { title: 'بروفايل Glitch', id: 'glitch-style', template: '[b][c][FF0000]G[00F2EA]L[FFFFFF]I[FF0000]T[00F2EA]C[FFFFFF]H', keywords: ['غليتش'] },
        { title: 'بروفايل الزعيم', id: 'the-boss-style', template: '[b][c][FFD700]T H E  B O S S\n[FFFFFF]     - 亗 -', keywords: ['بوس'] },
        // --- 75 NEW GAMING CODES ---
        { title: 'جراند ماستر', id: 'gaming-grandmaster', template: '[b][c][FF0000]G R A N D M A S T E R', keywords: ['جراند'] },
        { title: 'هيرويك', id: 'gaming-heroic', template: '[b][c][FFA500]H E R O I C ★', keywords: ['هيرويك'] },
        { title: 'ملك الـ M1887', id: 'gaming-m1887', template: '[b][c][A0A0A0]M1887 [FF0000]KING', keywords: ['شتقن'] },
        { title: 'لاعب سام', id: 'gaming-toxic', template: '[b][c][00FF00]T O X I C [FFFFFF]PLAYER ☣︎' },
        { title: 'لا يوجد مجال للضعفاء', id: 'gaming-noobs', template: '[b][c][A0A0A0]No place for [FF0000]NOOBS' },
        { title: 'وضع التدمير', id: 'gaming-destroyer', template: '[b][c][FF0000]D E S T R O Y E R', keywords: ['مدمر'] },
        { title: 'مطلوب حياً أو ميتاً', id: 'gaming-wanted', template: '[b][c][FFA500]W A N T E D\n[FFFFFF]DEAD OR ALIVE', keywords: ['مطلوب'] },
        { title: 'ملك الصحراء', id: 'gaming-desert-king', template: '[b][c][FFD700]DESERT KING\n[FFFF00]      🦅' },
        { title: 'لاعب تكتيكي', id: 'gaming-tactical', template: '[b][c][00FF00]TACTICAL GENIUS' },
        { title: 'لا رحمة للسكواد', id: 'gaming-no-mercy-2', template: '[b][c][FF0000]NO MERCY FOR SQUAD', keywords: ['رحمة'] },
        { title: 'قاتل مأجور', id: 'gaming-hitman', template: '[b][c][A0A0A0]H I T M A N', keywords: ['قاتل'] },
        { title: 'ملك الساحة', id: 'gaming-arena-king', template: '[b][c][FFD700]ARENA KING 👑' },
        { title: 'قوة الظلام', id: 'gaming-dark-force', template: '[b][c][FF00FF]DARK [000000]FORCE' },
        { title: 'صائد الرؤوس', id: 'gaming-head-hunter', template: '[b][c][A0A0A0]HEAD [FF0000]HUNTER' },
        { title: 'الخطر قادم', id: 'gaming-danger-coming', template: '[b][c][FFFF00]DANGER IS COMING ⚠︎' },
        { title: 'محترف سไนเปอร์', id: 'gaming-sniper-pro', template: '[b][c][00FF00]SNIPER [FFFFFF]PRO' },
        { title: 'أنا الكابوس', id: 'gaming-nightmare', template: '[b][c][FF00FF]I AM YOUR [A0A0A0]NIGHTMARE' },
        { title: 'الناجي الأخير', id: 'gaming-survivor', template: '[b][c][00FF00]LAST SURVIVOR' },
        { title: 'فريق الأحلام', id: 'gaming-dream-team', template: '[b][c][00F2EA]DREAM [FFFFFF]TEAM' },
        { title: 'أسطورة خالدة', id: 'gaming-immortal', template: '[b][c][FFD700]IMMORTAL LEGEND' },
    ],
    'misc-quotes-codes': [
        { title: 'مقولة: كن قوياً', id: 'quote-strong', template: '[b][c][00aaff]S T A Y\n[FFFFFF]S T R O N G', keywords: ['قوي'] },
        { title: 'مقولة: حلم كبير', id: 'quote-dream-big', template: '[b][c][FF00FF]DREAM\n[FFFFFF]  BIG', keywords: ['حلم'] },
        { title: 'مثل: اطلبوا العلم', id: 'quote-knowledge', template: '[b][c][6CABDD]اطلبوا العلم\n[FFFFFF]من المهد إلى اللحد', keywords: ['علم'] },
        { title: 'مثل: كن أنت التغيير', id: 'quote-be-change', template: '[b][c][00FF00]كن أنت التغيير الذي\n[FFFFFF]تريد أن تراه في العالم', keywords: ['تغيير'] },
        { title: 'كود ماتركس', id: 'hacker-matrix', template: '[00FF00][b]The Matrix Has You...', keywords: ['هاكر', 'ماتركس'] },
        { title: 'كود تحميل...', id: 'hacker-loading', template: '[00FF00][b]ACCESSING DATABASE...\n[FFFFFF]LOADING [00FF00]▓▓▓▓▓░░░░░', keywords: ['تحميل'] },
        { title: 'كود اختراق النظام', id: 'hacker-system', template: '[00FF00][b]> system_hack.exe\n[FF0000]ACCESS DENIED', keywords: ['اختراق'] },
        { title: 'كود ثنائي', id: 'hacker-binary', template: '[c][00FF00]01010101\n[FFFFFF]10101010\n[00FF00]01010101', keywords: ['binary'] },
        { title: 'حيوان: الأسد', id: 'animal-lion', template: '[b][c][FFA500]KING OF\n[FFFFFF]THE JUNGLE 🦁', keywords: ['أسد'] },
        { title: 'حيوان: الثعبان', id: 'animal-snake', template: '[b][c][00FF00]S S S S . . .\n[FFFFFF]      🐍', keywords: ['ثعبان'] },
        { title: 'حيوان: النسر', id: 'animal-eagle', template: '[b][c][E1D9D1]THE EAGLE\n[FFFFFF]HAS LANDED 🦅', keywords: ['نسر'] },
        { title: 'مقولة: الصمت حكمة', id: 'quote-silence', template: '[b][c][A0A0A0]الصمت أبلغ\n[FFFFFF]من الكلام', keywords: ['صمت', 'حكمة'] },
        { title: 'مقولة: عش اللحظة', id: 'quote-live-moment', template: '[b][c][33CC99]عش اللحظة', keywords: ['حياة'] },
        { title: 'برج الحمل ♈', id: 'zodiac-aries', template: '[c][b][FF8800]♈︎ ARIES ♈︎' },
        { title: 'برج الثور ♉', id: 'zodiac-taurus', template: '[c][b][009C3B]♉︎ TAURUS ♉︎' },
        { title: 'برج الجوزاء ♊', id: 'zodiac-gemini', template: '[c][b][FFFF00]♊︎ GEMINI ♊︎' },
        { title: 'برج السرطان ♋', id: 'zodiac-cancer', template: '[c][b][A0A0A0]♋︎ CANCER ♋︎' },
        { title: 'برج الأسد ♌', id: 'zodiac-leo', template: '[c][b][FFD700]♌︎ LEO ♌︎' },
        { title: 'برج العذراء ♍', id: 'zodiac-virgo', template: '[c][b][008000]♍︎ VIRGO ♍︎' },
        { title: 'برج الميزان ♎', id: 'zodiac-libra', template: '[c][b][6CABDD]♎︎ LIBRA ♎︎' },
        { title: 'برج العقرب ♏', id: 'zodiac-scorpio', template: '[c][b][FF0000]♏︎ SCORPIO ♏︎' },
        { title: 'برج القوس ♐', id: 'zodiac-sagittarius', template: '[c][b][9B1B30]♐︎ SAGITTARIUS ♐︎' },
        { title: 'برج الجدي ♑', id: 'zodiac-capricorn', template: '[c][b][6D7B8D]♑︎ CAPRICORN ♑︎' },
        { title: 'برج الدلو ♒', id: 'zodiac-aquarius', template: '[c][b][00F2EA]♒︎ AQUARIUS ♒︎' },
        { title: 'برج الحوت ♓', id: 'zodiac-pisces', template: '[c][b][5865F2]♓︎ PISCES ♓︎' },
        // --- 50 NEW MISC CODES ---
        { title: 'أنا لست مثاليًا', id: 'quote-not-perfect', template: '[c][b][A0A0A0]I\'m not perfect\nbut I\'m [FFFFFF]limited edition.' },
        { title: 'صنع في...', id: 'quote-made-in', template: '[c][b]MADE IN\n[FF0000]{{TEXT}}', defaultText: 'EGYPT' },
        { title: 'هدوء ما قبل العاصفة', id: 'quote-calm-storm', template: '[c][b][6CABDD]The calm before\n[A0A0A0]the storm.' },
        { title: 'لا تنظر للخلف', id: 'quote-dont-look-back', template: '[c][b]Don\'t look back\nyou\'re not going that way.' },
        { title: 'الطاقة الإيجابية', id: 'quote-positive-vibes', template: '[c][b][FFFF00]POSITIVE\n[33CC99]VIBES\n[FF00FF]ONLY' },
        { title: 'حالة: مزاج سيء', id: 'status-bad-mood', template: '[b][FF0000]● BAD MOOD' },
        { title: 'حالة: مزاج جيد', id: 'status-good-mood', template: '[b][00FF00]● GOOD MOOD' },
        { title: 'حيوان: الغوريلا', id: 'animal-gorilla', template: '[b][c][A0A0A0]SILVERBACK\n[000000]🦍' },
        { title: 'حيوان: الدب القطبي', id: 'animal-polar-bear', template: '[b][c][FFFFFF]POLAR POWER\n[A0A0A0]🐻‍❄️' },
        { title: 'مقولة: الحياة قصيرة', id: 'quote-life-short', template: '[c][b]Life is short.\nMake it [FFD700]legendary.' },
        { title: 'كود تحذير', id: 'misc-warning', template: '[c][b][FFFF00]⚠ WARNING ⚠\n[FFFFFF]AWESOME PLAYER' },
        { title: 'كود منطقة محظورة', id: 'misc-restricted-area', template: '[c][b][FF0000]RESTRICTED\n[A0A0A0]AREA' },
        { title: 'موسيقى هي حياتي', id: 'quote-music-life', template: '[c][b][FF00FF]MUSIC\n[FFFFFF]IS MY\n[00F2EA]LIFE' },
        { title: 'فنان', id: 'misc-artist', template: '[c][b][33CC99]A R T I S T 🎨' },
        { title: 'شاعر', id: 'misc-poet', template: '[c][b][A0A0A0]P O E T ✒️' },
        { title: 'حالة: أفكر', id: 'status-thinking', template: '[b][6CABDD]● Thinking...' },
        { title: 'أنا مختلف', id: 'quote-different', template: '[c][b]I\'m not weird\nI\'m [FF00FF]different.' },
        { title: 'لا تستسلم أبدا', id: 'quote-never-surrender', template: '[c][b][FF0000]NEVER SURRENDER' },
        { title: 'العمل الجاد', id: 'quote-hard-work', template: '[c][b]Hard work\n[FFD700]pays off.' },
        { title: 'كن أسطورة نفسك', id: 'quote-be-legend', template: '[c][b]Be your own\n[FFD700]LEGEND' },
    ],
    'social-media-codes': [
        { title: 'انستغرام (ستايل نجوم)', id: 'insta-stars', template: '[b][c]╭─╮\n︱◯֯︱★ɪɴꜱᴛᴀ★┊[ff0000]{{TEXT}}\n╰─╯', defaultText: 'اسمك', keywords: ['انستا'] },
        { title: 'يوتيوب', id: 'youtube', template: '[b][c]╭─╮\n︱▶︱ʏᴏᴜᴛᴜʙᴇ┊[FF0000]{{TEXT}}\n╰─╯', defaultText: 'قناتك' },
        { title: 'تيك توك 🎵', id: 'tiktok', template: '[b][c]╭─╮\n︱ꚠ︱ᴛɪᴋᴛᴏᴋ┊[FF00FF]{{TEXT}}\n╰─╯', defaultText: 'حسابك' },
        { title: 'فيسبوك', id: 'facebook', template: '[b][c]╭─╮\n︱ⓕ︱ꜰᴀᴄᴇʙᴏᴏᴋ┊[0000FF]{{TEXT}}\n╰─╯', defaultText: 'صفحتك', keywords: ['فيس'] },
        { title: 'ديسكورد', id: 'discord', template: '[b][c][5865F2]Discord\n[FFFFFF]{{TEXT}}', defaultText: 'User#1234' },
        { title: 'تويتر (X)', id: 'twitter-x', template: '[b][c][000000]𝕏\n[FFFFFF]{{TEXT}}', defaultText: 'حسابك', keywords: ['تويتر', 'اكس'] },
        { title: 'سناب شات', id: 'snapchat', template: '[b][c][FFFF00]Snapchat 👻\n[000000]{{TEXT}}', defaultText: 'حسابك', keywords: ['سناب'] },
        { title: 'تليجرام', id: 'telegram', template: '[b][c][00aaff]Telegram ✈️\n[FFFFFF]{{TEXT}}', defaultText: 'قناتك', keywords: ['تليجرام'] },
        { title: 'شريط الموسيقى', id: 'music-player', template: '[33CC99]▷◉───────00:00', keywords: ['اغنية'] },
        { title: 'رمز واي فاي', id: 'new-wifi', template: '[b][c][A0A0A0]Searching for WiFi\n[00FF00]   📶' },
        { title: 'رمز الهاتف', id: 'new-call-me', template: '[b][c][00FF00]CALL ME\n[FFFFFF]     📞', keywords: ['اتصل'] },
        { title: 'واتساب', id: 'whatsapp', template: '[b][c][00FF00]WhatsApp\n[FFFFFF]{{TEXT}}', defaultText: 'رقمك', keywords: ['واتس'] },
    ]
};